Milestone 2: user interface
lirad/ruby-tic-tac-toe pull request #2
Opened 2020-09-01 12:51 UTC by mahmoud717

we created a user interface that has an infrastructure of the game using comments and also does the following:
1. register both players' names and tokens.
2. askes the players for a line and a column and registers them in separate values for each player.
3. display the chosen play after the player selects it.

2020-09-01 13:09 UTC, santiago-rodrig commented
# Pull Request under review by @santiago-rodrig (TSE)

2020-09-01 13:21 UTC, santiago-rodrig commented on bin/main
> +p 'Hey player1, whats your name?'
```suggestion
puts "Hey player 1, what's your name?"
```

2020-09-01 13:21 UTC, santiago-rodrig commented on bin/main
> +p 'Hey player2, whats your name?'
```suggestion
puts "Hey player 2, what's your name?"
```

2020-09-01 13:22 UTC, santiago-rodrig commented on bin/main
> +                end
```suggestion
player2_token = player1_token == 'x' ? 'o' : 'x'
```

2020-09-01 13:22 UTC, santiago-rodrig commented on bin/main
> +p "hello #{player2}, your token is #{player2_token}"
```suggestion
puts "hello #{player2}, your token is #{player2_token}"
```

2020-09-01 13:25 UTC, santiago-rodrig commented on bin/main
> +5.times do
This is not OK, you should have a `game_over` boolean variable that tells when the game is over and iterate until this variable is `true`.

2020-09-01 13:36 UTC, santiago-dev96 requested changes
# Changes required 🛠️ 

This is a good start, but some things need to be fixed, please read the comments I left there to help, the goal of this project is to fake the game flow, that doesn't mean using `5.times`, because that doesn't take into account the draw state of the game, or how the game looks when X wins or O wins, you must think on how the user will perceive those parts of the game.

Another thing, don't make the user input row and column when just passing a number will suffice, and print the board after every player's turn.

### [OPTIONAL]

You have some typos in your `readme.md`, and this file should have a name with just uppercase letters, like `README.md`, apart from that, congratulations for including a `README.md` file even though it is not required yet for this milestone.

## What to do now?

Implement the required changes and submit another CRR.

You can find me in slack as **srodrig**, happy coding! :wave:

2020-09-01 13:36 UTC, santiago-rodrig commented on bin/main
> +  # next
This is not a good approach to mocking the game flow, first, the positions in the board should be plain integers, starting at 1 and ending at 9.

1 | 2 | 3
4 | 5 | 6
7 | 8 | 9

That's the expected aspect of the board, of course for this milestone it is not required to change the state of the board in any form, so you can just display it after every player's turn.

You can mock all the possible scenarios, X wins, O wins, and draw, but make sure you have some sort of counter and that the scenario is selected at random (`rand(3)` can help), think about that by yourselves.

2020-09-01 15:38 UTC, mikenath223 requested changes
### Hi Team 👋

Nice work so far on this. 👌👌


- [ ] Sorry this wasn't mentioned in the least review but please add a rubocop.yml file as [mentioned here](https://github.com/microverseinc/linters-config/tree/master/ruby).

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-09-01 15:39 UTC, mikenath223 commented on bin/main
> +  puts "Hurray, #{player2} you win"
- [ ] Notice that you are repeating the same process for each player's turn. Consider extracting this as a method you would call in the loop for each player turn.

2020-09-02 10:21 UTC, mikenath223 requested changes
### Hi again Team. 👋

Good job fixing an issue referenced in the previous review.👍

However, kindly take note of the comments below as this was referenced in the last review. It's important you follow the DRY principle.👇

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-09-02 10:22 UTC, mikenath223 commented on bin/main
> +  puts "Hurray, #{player2} you win"
> * [ ]  Notice that you are repeating the same process for each player's turn. Consider extracting this as a method you would call in the loop for each player turn.

Please consider extracting the repeated code in a method like this and calling it in each player's turn within the loop:
```
def each_turn(player)
  puts "#{player}, choose a position"
  player_position = gets.chomp
  # check if the position is valid
  # confirm selected move
  puts "You selected position #{player_position}."
  # display the board
  display_board
end
```

2020-09-02 10:23 UTC, mikenath223 commented on bin/main
> +  display_board
> * [ ]  Notice that you are repeating the same process for each player's turn. Consider extracting this as a method you would call in the loop for each player turn.

Please consider extracting the repeated code in a method like this and calling it in each player's turn within the loop:
```
def each_turn(player)
  puts "#{player}, choose a position"
  player_position = gets.chomp
  # check if the position is valid
  # confirm selected move
  puts "You selected position #{player_position}."
  # display the board
  display_board
end
```

2020-09-02 15:48 UTC, Dandush03 commented
# Status: :rocket: Project Approved :rocket: 
## Great job applying does changes
# Happy Coding! :computer: :nerd_face:

2020-09-03 12:23 UTC, merged